/**
 * Theme generation script
 * Generates CSS files from TypeScript token definitions
 *
 * Usage: npx tsx scripts/generate-theme.ts
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const themesDir = path.join(rootDir, 'src', 'themes');
const generatedDir = path.join(themesDir, 'generated');

// Import token definitions directly
import { baseTokens } from '../src/themes/definitions/base.js';
import { typographyTokens } from '../src/themes/definitions/typography.js';
import { colorTokens } from '../src/themes/definitions/colors.js';
import { phaseTokens } from '../src/themes/definitions/phases.js';
import { graphTokens } from '../src/themes/definitions/graph.js';
import { componentTokens } from '../src/themes/definitions/components.js';
import { darkOverrides } from '../src/themes/variants/dark.js';

// Aggregate all tokens
const allTokens = {
  ...baseTokens,
  ...typographyTokens,
  ...colorTokens,
  ...phaseTokens,
  ...graphTokens,
  ...componentTokens,
} as const;

type CssVarName = keyof typeof allTokens;

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function generateDefaultCss(tokens: Record<string, string>): string {
  const lines = [
    '/**',
    ' * Default theme - auto-generated from TypeScript definitions',
    ' * DO NOT EDIT DIRECTLY - modify /src/themes/definitions/ instead',
    ' */',
    ':root {',
  ];

  for (const [name, value] of Object.entries(tokens)) {
    lines.push(`  --${name}: ${value};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}

function generateDarkCss(overrides: Partial<Record<CssVarName, string>>): string {
  const lines = [
    '/**',
    ' * Dark theme overrides - auto-generated from TypeScript definitions',
    ' * DO NOT EDIT DIRECTLY - modify /src/themes/variants/dark.ts instead',
    ' */',
    '[data-theme="dark"] {',
  ];

  for (const [name, value] of Object.entries(overrides)) {
    if (value !== undefined) {
      lines.push(`  --${name}: ${value};`);
    }
  }

  lines.push('}', '');
  return lines.join('\n');
}

function generateIndexCss(): string {
  return [
    '/**',
    ' * Theme CSS aggregator - auto-generated',
    ' * DO NOT EDIT DIRECTLY',
    ' */',
    '@import "./default.css";',
    '@import "./dark.css";',
    '',
  ].join('\n');
}

function generateTypesFile(tokens: Record<string, string>): string {
  const tokenNames = Object.keys(tokens);
  const lines = [
    '/**',
    ' * Generated CSS variable types',
    ' * DO NOT EDIT DIRECTLY - this file is auto-generated by scripts/generate-theme.ts',
    ' */',
    '',
    '// Union of all valid CSS variable names (without -- prefix)',
    `export type CssVarName = ${tokenNames.map((n) => `'${n}'`).join(' | ')};`,
    '',
    '// Union of all valid CSS variable names (with -- prefix)',
    `export type CssVar = \`--\${CssVarName}\`;`,
    '',
  ];

  return lines.join('\n');
}

function main(): void {
  console.log('Generating theme CSS files...');

  // Ensure generated directory exists
  ensureDir(generatedDir);

  // Generate default.css
  const defaultCss = generateDefaultCss(allTokens);
  const defaultPath = path.join(generatedDir, 'default.css');
  fs.writeFileSync(defaultPath, defaultCss);
  console.log(`  Created: ${path.relative(rootDir, defaultPath)}`);

  // Generate dark.css
  const darkCss = generateDarkCss(darkOverrides);
  const darkPath = path.join(generatedDir, 'dark.css');
  fs.writeFileSync(darkPath, darkCss);
  console.log(`  Created: ${path.relative(rootDir, darkPath)}`);

  // Generate index.css
  const indexCss = generateIndexCss();
  const indexPath = path.join(generatedDir, 'index.css');
  fs.writeFileSync(indexPath, indexCss);
  console.log(`  Created: ${path.relative(rootDir, indexPath)}`);

  // Generate types file
  const typesContent = generateTypesFile(allTokens);
  const typesPath = path.join(themesDir, 'types.generated.ts');
  fs.writeFileSync(typesPath, typesContent);
  console.log(`  Created: ${path.relative(rootDir, typesPath)}`);

  console.log('Theme generation complete!');
}

main();
